# Generated by Django 4.1.7 on 2023-04-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CExchange', '0003_exchange_deal_date_exchange_init_date_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='deal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='init_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
