# Generated by Django 4.2 on 2023-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CExchange', '0004_alter_complaint_date_alter_deposit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='Txid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='currency',
            field=models.CharField(choices=[('HKD', 'HKD'), ('BTC', 'BTC'), ('BCH', 'BCH'), ('DASH', 'DASH'), ('LTC', 'LTC')], default='BTC', max_length=4),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='deal_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='taken_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('HKD', 'HKD'), ('BTC', 'BTC'), ('BCH', 'BCH'), ('DASH', 'DASH'), ('LTC', 'LTC')], default='HKD', max_length=4),
        ),
    ]
